# rake js:routes

namespace :js do
  desc "Generate JavaScript routes from Rails routes"
  task routes: :environment do
    output_file = Rails.root.join("app/frontend/lib/routes.ts")

    # Ensure the directory exists
    FileUtils.mkdir_p(File.dirname(output_file))

    # Generate the routes file
    generated_routes = JsRoutes.generate
    File.write(output_file, "// @ts-nocheck\n#{generated_routes}")

    # Append *_path aliases for convenience in TS/JS imports.
    route_names = generated_routes.scan(/^export const (\w+) =/).flatten
    path_aliases = route_names.reject { |name| name.end_with?("_path") }.map do |name|
      "export const #{name}_path = #{name};"
    end
    unless path_aliases.empty?
      File.open(output_file, "a") do |file|
        file.puts
        file.puts "// Path aliases (auto-generated by js:routes task)."
        file.puts path_aliases.join("\n")
      end
    end

    puts "Routes generated at #{output_file}"
  end
end
