// TypesFromSerializers CacheKey e1d9ed757f0ecd534155c8e7352dc71f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Achievement {
  id: string
  category: string
  description?: string
  hidden?: boolean
  icon?: string
  key: string
  name: string
  pointsReward: number
  tier?: string
}
