// TypesFromSerializers CacheKey 6e8dd27516d9be29543cbe3a762f1a18
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Event {
  id: string
  description?: string
  location?: string
  name?: string
  price: number
  slug?: string
  startsAt?: string
}
