// TypesFromSerializers CacheKey ac8d5e8b33cd3adf98694ba428ecea95
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Event {
  id: string
  description?: string
  location?: string
  name?: string
  price: number
  startsAt?: string
}
