// TypesFromSerializers CacheKey 7f89511ed321d5775756aacb15237cfa
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface GamificationEvent {
  id: string
  createdAt: string
  eventType: string
  metadata?: Record<string, any>
  pointsEarned: number
}
