// TypesFromSerializers CacheKey ec35e0be16b810a1552b40616bf8175f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface GreetingList {
  id: string
  createdAt: string
  published: boolean
  title: string
  totalLixi: number
  totalRecipients: number
  totalViews: number
}
