// TypesFromSerializers CacheKey 2d119e986432d754db9a5a9fe09ffbcb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Greeting {
  id: string
  createdAt: string
  message?: string
  paymentInfo: object
  paymentMethod?: string
  published: boolean
  title: string
  totalGaveLixi: number
  totalLixiReceived: number
  totalRecipients: number
  totalViews: number
  updatedAt: string
}
