// TypesFromSerializers CacheKey e3531f7881dadd3edf0fd48def1b5c12
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface LifeWeekEntry {
  id: string
  createdAt: string
  dateRange: any
  lifeStage: string
  memories?: string
  notes?: string
  updatedAt: string
  weekNumber: number
  yearAndWeek: any
}
