// TypesFromSerializers CacheKey f37449b780428378fc091002abfbe2e6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type UserMinimal from './UserMinimal'

export default interface Mood {
  id: string
  createdAt: string
  entryDate: string
  level: number
  moodColor: string
  moodEmoji: string
  moodName: string
  notes?: string
  updatedAt: string
  user: UserMinimal
}
