// TypesFromSerializers CacheKey d2b719dc7d09f41c8325c33627a815a9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Mood {
  id: string
  createdAt: string
  entryDate: string
  level: number
  moodColor: string
  moodEmoji: string
  moodName: string
  notes?: string
  updatedAt: string
  user: any
}
