// TypesFromSerializers CacheKey 73e99fb0c758718b06afaea943fad6fd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface NotePost {
  author: any
  category: any
  content: any
  date: any
  excerpt: any
  featuredImage: any
  published: any
  slug: any
  tags: any
  title: any
  urlPath: any
}
