// TypesFromSerializers CacheKey 3c49834a7488ef51dc9d0c0c486df554
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Recipient {
  id: string
  gaveLixi: boolean
  lixiAmount: number
  name: string
  token: string
  viewUrl: string
  viewedAt?: string
}
