// TypesFromSerializers CacheKey 459fd1e5718c8dd435217e98d18848a5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Event from './Event'
import type User from './User'

export default interface Registration {
  id: string
  createdAt: string
  event: Event
  howHeard?: string
  user: User
}
