// TypesFromSerializers CacheKey 2c8ce4a75dba63eb4c3116b640069520
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Event from './Event'

export default interface Registration {
  id: string
  createdAt: string
  email?: string
  event: Event
  howHeard?: string
  name?: string
}
