// TypesFromSerializers CacheKey 98b9823a727c02857ac1a98b70677122
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface RegistrationForm {
  id: string
  email?: string
  howHeard?: string
  name?: string
}
