// TypesFromSerializers CacheKey c0200bb2ecd0bd04ebdb713f799d7be1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Event from './Event'

export default interface Registration {
  id: string
  createdAt: string
  email?: string
  event: Event
  howHeard?: string
  name?: string
}
