// TypesFromSerializers CacheKey c37d4d1adaeb3af8af7ea99bc9c72d42
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type User from './User'

export default interface RegistrationForm {
  id: string
  howHeard?: string
  user: User
  userId?: string
}
