// TypesFromSerializers CacheKey 3cd73eb4113388b2a9ad6dbe34b0bd96
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface UserAchievement {
  id: string
  achievement: any
  progress: number
  unlockedAt: string
}
