// TypesFromSerializers CacheKey 086480964a498b3997518af358589b3e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface UserDetailed {
  id: string
  avatarUrl?: string
  createdAt: string
  email: string
  name?: string
  provider?: string
  role: 'user' | 'admin'
  uid?: string
  updatedAt: string
}
