// TypesFromSerializers CacheKey f342f25f28390fbda72cddfe62cbdd73
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface User {
  id: string
  avatarUrl?: string
  createdAt: string
  email: string
  name?: string
  role: 'user' | 'admin'
}
