// TypesFromSerializers CacheKey e52c6f457520e66c9a53fd82eb376576
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface UserMinimal {
  id: string
  avatarUrl?: string
  email: string
  name?: string
}
