// TypesFromSerializers CacheKey 92a3ebc00ee0c8a0e838da71705a266c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface UserBasic {
  id: string
  avatarUrl?: string
  createdAt: string
  email: string
  name?: string
  role: 'user' | 'admin'
}
