// TypesFromSerializers CacheKey 9fd9790dfdcdbbd037c3603e46bf352a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface User {
  id: string
  avatarUrl?: string
  birthDate?: string
  createdAt: string
  email: string
  name?: string
  role: 'user' | 'admin'
}
