// TypesFromSerializers CacheKey 2009ab81c464151e9553d93c55b3c5d7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Achievement from './Achievement'

export default interface UserAchievement {
  id: string
  achievement: Achievement
  progress: number
  unlockedAt: string
}
