// TypesFromSerializers CacheKey fabd71b8285caba30ee7421938bb3a05
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface UserStats {
  currentLevel: number
  currentMoodStreak: number
  currentWritingStreak: number
  levelProgress: number
  longestMoodStreak: number
  longestWritingStreak: number
  pointsToNextLevel: number
  totalEventsAttended: number
  totalGreatMoods: number
  totalMoodsLogged: number
  totalNotesWithDetails: number
  totalPoints: number
  totalPostsWritten: number
}
