// TypesFromSerializers CacheKey 583ab0a7bd48c3d32290aebb1c92f2e8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type UserMinimal from './UserMinimal'

export default interface Version {
  id: number
  createdAt?: string
  event: string
  itemId: string
  itemType: string
  object?: string
  objectChanges?: string
  user: UserMinimal
}
